# Generated by Django 4.0.5 on 2022-10-09 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0057_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='realestate.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='realestate.city'),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='realestate.region'),
        ),
        migrations.AlterField(
            model_name='product',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='realestate.room'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='realestate.type'),
        ),
    ]
